# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-04 15:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(choices=[('free', 'Free'), ('strd', 'Standard'), ('prm', 'Premium')], max_length=120, verbose_name='Plan')),
                ('start_date', models.DateField(default=django.utils.timezone.now, verbose_name='Start date')),
                ('active', models.BooleanField(default=True, editable=False, help_text='this plan is  active ?', verbose_name='Active')),
                ('period_count', models.IntegerField(blank=True, default=1, null=True, verbose_name='Number of interval')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Store')),
            ],
            options={
                'ordering': ['start_date'],
                'verbose_name': 'Billing',
                'verbose_name_plural': 'Billing',
            },
        ),
    ]
